# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[(b'D', b'Dinner'), (b'B', b'bar_menu'), (b'W', b'Wines')], max_length=2),
        ),
    ]
