# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
