# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170828_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
