# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170816_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.ImageField(upload_to=b'images/%Y/%m/%d'),
        ),
    ]
