# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170816_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutu',
            options={'verbose_name': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='pic',
            options={'verbose_name': 'Pictures'},
        ),
    ]
