# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170816_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutU',
            new_name='AboutUs',
        ),
    ]
